import React, { useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import MaterialDesignIcons from "@react-native-vector-icons/material-design-icons";
import { ScreenHeader } from "@/src/components/screen-header";
import { getNearby, NearbyPlace } from "@/src/data/api";
import { useTheme, spacing, radius } from "@/src/theme";

export default function Nearby() {
  const { colors } = useTheme(); const router = useRouter();
  const p = useLocalSearchParams<{lat:string;lon:string;name:string}>();
  const lat=Number(p.lat), lon=Number(p.lon); const [kind,setKind]=useState<"hospital"|"hotel">("hospital"); const [items,setItems]=useState<NearbyPlace[]>([]); const [busy,setBusy]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{(async()=>{setBusy(true);const r=await getNearby(lat,lon,kind);if(r.success)setItems(r.data);else setError(r.error);setBusy(false)})()},[kind,lat,lon]);
  return <View style={[styles.root,{backgroundColor:colors.surface}]}><ScreenHeader title="Nearby" subtitle={p.name ? `Around ${p.name}` : "Nearby places"}/><View style={styles.tabs}><Pressable onPress={()=>setKind("hospital")} style={[styles.tab,{backgroundColor:kind==="hospital"?colors.brandPrimary:colors.surfaceSecondary}]}><MaterialDesignIcons name="hospital-building" size={19} color={kind==="hospital"?colors.onBrandPrimary:colors.onSurface}/><Text style={{color:kind==="hospital"?colors.onBrandPrimary:colors.onSurface,fontWeight:"800"}}>Hospitals</Text></Pressable><Pressable onPress={()=>setKind("hotel")} style={[styles.tab,{backgroundColor:kind==="hotel"?colors.brandPrimary:colors.surfaceSecondary}]}><MaterialDesignIcons name="bed-outline" size={19} color={kind==="hotel"?colors.onBrandPrimary:colors.onSurface}/><Text style={{color:kind==="hotel"?colors.onBrandPrimary:colors.onSurface,fontWeight:"800"}}>Hotels</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}>{busy?<ActivityIndicator color={colors.brandPrimary} style={{marginTop:30}}/>:error?<Text style={{color:colors.error}}>{error}</Text>:items.length===0?<Text style={[styles.empty,{color:colors.muted}]}>No mapped places found nearby.</Text>:items.map(x=><View key={x.id} style={[styles.card,{backgroundColor:colors.surfaceSecondary,borderColor:colors.border}]}><View style={[styles.icon,{backgroundColor:colors.brandTertiary}]}><MaterialDesignIcons name={kind==="hospital"?"hospital-building":"bed-outline"} size={22} color={colors.brandPrimary}/></View><View style={{flex:1}}><Text style={[styles.name,{color:colors.onSurface}]}>{x.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{x.distanceKm} km away{x.address?` · ${x.address}`:""}</Text>{x.phone&&<Text style={[styles.meta,{color:colors.muted}]}>{x.phone}</Text>}</View>{x.phone&&<Pressable onPress={()=>Linking.openURL(`tel:${x.phone}`)} style={[styles.circle,{backgroundColor:colors.brandPrimary}]}><MaterialDesignIcons name="phone" size={18} color={colors.onBrandPrimary}/></Pressable>}</View>)}<Pressable onPress={()=>router.push({pathname:"/map",params:{lat,lon,name:p.name||"Location"}})} style={[styles.mapBtn,{backgroundColor:colors.surfaceTertiary}]}><MaterialDesignIcons name="map" size={20} color={colors.onSurface}/><Text style={{color:colors.onSurface,fontWeight:"800"}}>View this area on map</Text></Pressable></ScrollView></View>
}
const styles=StyleSheet.create({root:{flex:1},tabs:{flexDirection:"row",gap:spacing.sm,padding:spacing.lg,paddingBottom:0},tab:{flex:1,minHeight:46,borderRadius:radius.md,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:7},content:{padding:spacing.lg,paddingBottom:spacing.xxxl},card:{borderWidth:1,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.sm,flexDirection:"row",alignItems:"center",gap:spacing.md},icon:{width:42,height:42,borderRadius:11,alignItems:"center",justifyContent:"center"},name:{fontSize:14,fontWeight:"800"},meta:{fontSize:11,marginTop:3},circle:{width:38,height:38,borderRadius:19,alignItems:"center",justifyContent:"center"},empty:{textAlign:"center",marginTop:30},mapBtn:{height:50,borderRadius:radius.md,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8,marginTop:spacing.md}});
